name       : protonvpn-gui
version    : 1.12.0
release    : 6
source     :
    - https://github.com/ProtonVPN/linux-app/archive/refs/tags/1.12.0.tar.gz : 708dd5aa04a12963361a7a13188c65938b94adc268608e341faa2985312e7f94
license    : GPL-3.0-or-later
component  : network.clients
summary    : Official ProtonVPN GUI client.
description: |
    Official ProtonVPN GUI.
builddeps  :
    - pkgconfig(ayatana-appindicator3-0.1)
    - pkgconfig(py3cairo)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(webkit2gtk-4.0)
    - python-psutil
rundeps    :
    - libayatana-appindicator
    - protonvpn-nm-lib
    - python-gobject
    - python-psutil
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-libayatana-appindicator.patch
build      : |
    %python3_setup
install    : |
    %python3_install

    install -Dm00644 protonvpn.desktop $installdir/usr/share/applications/protonvpn.desktop
    install -Dm00644 protonvpn_gui/assets/icons/protonvpn-logo.png $installdir/usr/share/pixmaps/protonvpn-logo.png
