name       : protonvpn-gui
version    : 1.7.0
release    : 3
source     :
    - https://github.com/ProtonVPN/linux-app/archive/refs/tags/1.7.0.tar.gz : 59115d756c007c94dc5c498b726576ec2b4db4149abbe17c546dc7cee7f57286
license    : GPL-3.0-or-later
component  : network.clients
summary    : Official ProtonVPN GUI client.
description: |
    Official ProtonVPN GUI.
builddeps  :
    - pkgconfig(ayatana-appindicator3-0.1)
    - pkgconfig(pycairo)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(webkit2gtk-4.0)
    - python-psutil
rundeps    :
    - libayatana-appindicator
    - protonvpn-nm-lib
    - python-gobject
    - python-psutil
    - python-systemd
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-libayatana-appindicator.patch
build      : |
    %python3_setup
install    : |
    %python3_install

    install -Dm00644 protonvpn.desktop $installdir/usr/share/applications/protonvpn.desktop
    install -Dm00644 protonvpn_gui/assets/icons/protonvpn-logo.png $installdir/usr/share/pixmaps/protonvpn-logo.png
